apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-app
  labels:
    app: node-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-express-app
  template:
    metadata:
      labels:
        app: node-express-app
    spec:
      containers:
      - name: node-express-app
        # Replace with your actual image name and registry
        image: ramkaje341/simplenodeapp:latest 
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
